//! Build script — only active when the `embedded-key` feature is enabled.
//!
//! When active, reads `CURSEFORGE_API_KEY` from the build-time environment
//! and writes an XOR-obfuscated copy of it into `$OUT_DIR/embedded_key.rs`.
//! The example `curseforge_with_embedded_key.rs` `include!`s that file and
//! decodes the bytes at runtime into a `secrecy::SecretString`.
//!
//! This is **obfuscation, not encryption**. The deobfuscation mask lives
//! in the binary alongside the obfuscated bytes, so a reverse engineer
//! with a debugger can always recover the key. What this buys you:
//!
//! - `strings <binary>` does not reveal the key.
//! - Casual grep-based extraction fails.
//! - The plaintext is never stored as a contiguous UTF-8 blob in the
//!   binary's read-only data section.
//!
//! What it does not buy you: meaningful cryptographic protection. If the
//! key leaks, rotate it in the CurseForge developer console and ship a
//! new build.

use std::env;
use std::fs;
use std::path::PathBuf;

const KEY_ENV: &str = "CURSEFORGE_API_KEY";

fn main() {
    // Track this single env var so cargo reruns build.rs when it changes.
    // We intentionally do NOT print the value anywhere — cargo's build log
    // captures stderr/stdout of this script.
    println!("cargo:rerun-if-env-changed={KEY_ENV}");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("embedded_key.rs");

    // Feature gate: when the `embedded-key` feature is off, write a stub
    // and stop. Library users who never touch the feature pay nothing
    // beyond one file-write.
    if env::var_os("CARGO_FEATURE_EMBEDDED_KEY").is_none() {
        write_stub(&dest);
        return;
    }

    match env::var(KEY_ENV) {
        Ok(key) if !key.is_empty() => {
            write_obfuscated(&dest, &key);
        }
        _ => {
            // Feature is on but no key is available at build time (e.g. a
            // local `cargo build --features embedded-key` with the secret
            // unset). Write a "not embedded" stub so the example compiles
            // and surfaces a clear runtime error.
            write_stub(&dest);
        }
    }
}

fn write_stub(dest: &PathBuf) {
    let src = "// Auto-generated by build.rs — do not edit.\n\
               // No key was embedded at build time.\n\
               #[allow(dead_code)]\n\
               const EMBEDDED_AT_BUILD: bool = false;\n\
               #[allow(dead_code)]\n\
               const OBFUSCATED_KEY: &[u8] = &[];\n\
               #[allow(dead_code)]\n\
               const OBFUSCATION_MASK: &[u8] = &[];\n";
    fs::write(dest, src).expect("write stub embedded_key.rs");
}

fn write_obfuscated(dest: &PathBuf, key: &str) {
    let key_bytes = key.as_bytes();
    let mask = derive_mask(key_bytes.len(), seed_from_env());
    let obf: Vec<u8> = key_bytes
        .iter()
        .zip(mask.iter())
        .map(|(b, m)| b ^ m)
        .collect();

    let src = format!(
        "// Auto-generated by build.rs — do not edit.\n\
         // CurseForge API key was embedded at build time, XOR-obfuscated\n\
         // with a per-build pseudorandom mask. See build.rs for the full\n\
         // security discussion — this is obfuscation, not encryption.\n\
         #[allow(dead_code)]\n\
         const EMBEDDED_AT_BUILD: bool = true;\n\
         #[allow(dead_code)]\n\
         const OBFUSCATED_KEY: &[u8] = &{obf:?};\n\
         #[allow(dead_code)]\n\
         const OBFUSCATION_MASK: &[u8] = &{mask:?};\n",
    );
    fs::write(dest, src).expect("write obfuscated embedded_key.rs");
}

/// Seed the mask from a stable, build-visible source so repeated
/// identical-input builds produce different bytes. We mix in the
/// nanosecond-precision wallclock at build time — this is not secret
/// (cargo logs timestamps) but it makes two otherwise-identical binaries
/// differ, which frustrates diff-based extraction attempts.
fn seed_from_env() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0x9E37_79B9_7F4A_7C15)
}

/// Produce a byte string the exact length of the key, so the XOR has no
/// discernible period. Uses a splitmix64-style step — enough to produce
/// byte-level variability without pulling in a crypto dep at build time.
fn derive_mask(len: usize, mut state: u64) -> Vec<u8> {
    if state == 0 {
        state = 0x9E37_79B9_7F4A_7C15;
    }
    let mut out = Vec::with_capacity(len);
    for _ in 0..len {
        state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^= z >> 31;
        out.push((z & 0xFF) as u8);
    }
    out
}
