use serde::{Deserialize, Serialize};

/// The type of mod loader for an instance.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LoaderType {
    Vanilla,
    Fabric,
    Forge,
    Neoforge,
    Quilt,
}

impl LoaderType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Vanilla => "vanilla",
            Self::Fabric => "fabric",
            Self::Forge => "forge",
            Self::Neoforge => "neoforge",
            Self::Quilt => "quilt",
        }
    }

    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "vanilla" => Some(Self::Vanilla),
            "fabric" => Some(Self::Fabric),
            "forge" => Some(Self::Forge),
            "neoforge" => Some(Self::Neoforge),
            "quilt" => Some(Self::Quilt),
            _ => None,
        }
    }
}

impl std::fmt::Display for LoaderType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Configuration for a Minecraft instance, stored in the database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstanceConfig {
    /// Unique integer ID (auto-generated by SQLite).
    pub id: i64,
    /// Display name chosen by the user.
    pub name: String,
    /// Minecraft version (e.g., "1.21.4").
    pub minecraft_version: String,
    /// Mod loader type.
    pub loader: LoaderType,
    /// Mod loader version (e.g., "0.16.14"), None for Vanilla.
    pub loader_version: Option<String>,
    /// Required Java major version (e.g., "21").
    pub java_version: Option<String>,
    /// ISO 8601 creation timestamp.
    pub created_at: String,
    /// ISO 8601 timestamp of last play session.
    pub last_played: Option<String>,
    /// Path to the instance directory on disk.
    pub instance_path: String,
}

/// Parameters for creating a new instance (before ID/path are assigned).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateInstanceParams {
    pub name: String,
    pub minecraft_version: String,
    pub loader: LoaderType,
    pub loader_version: Option<String>,
    pub java_version: Option<String>,
}
