//! Secure CurseForge API-key flow using a **build-time embedded key**.
//!
//! This is the companion to `curseforge_with_keyring.rs`. Use this
//! pattern when you are shipping an application under **your own**
//! CurseForge developer key and do not want every end-user to supply
//! their own — the key is baked into the binary at CI-build time and
//! decoded at runtime.
//!
//! # Threat model — READ THIS FIRST
//!
//! The key is XOR-obfuscated against a per-build pseudorandom mask. Both
//! the obfuscated bytes and the mask live in the binary. This means:
//!
//! **What it defends against**
//! - `strings <binary> | grep` — the plaintext key is not a contiguous
//!   UTF-8 run anywhere in the binary.
//! - Casual static inspection — a user who pokes around in a hex editor
//!   will not spot the key.
//! - `Debug` / log leakage — the decoded plaintext is immediately wrapped
//!   in `secrecy::SecretString`, which refuses to appear in `Debug`
//!   output and zeros its backing bytes on drop.
//!
//! **What it does NOT defend against**
//! - A debugger attached to the running process. Someone with `gdb` /
//!   `x64dbg` / WinDbg can set a breakpoint on `expose_secret` and read
//!   the plaintext. Budget: 5 minutes.
//! - Patient reverse-engineering of the binary. The XOR loop and the two
//!   byte slices are visible in disassembly; someone with Ghidra or IDA
//!   can recover the key.
//!
//! This is **obfuscation**, not encryption. Real cryptographic protection
//! of a secret embedded in a client binary is impossible — the binary
//! must contain everything needed to decrypt itself, so a motivated
//! attacker can always replicate the decryption.
//!
//! The practical model: CurseForge's developer keys are issued expecting
//! this kind of embedding. If your key leaks into the wild, rotate it in
//! the CurseForge console (<https://console.curseforge.com/>) and ship a
//! new build. Obfuscation raises the extraction cost from *seconds* to
//! *a motivated afternoon*; it does not make the key unrecoverable.
//!
//! For secrets that must *not* leak under any circumstances (billing
//! APIs, user-impersonation tokens, etc.), proxy them through a server
//! your client talks to — do not embed them.
//!
//! # Build
//!
//! ```sh
//! # Local dev (will fail at runtime with a clear message):
//! cargo run --features embedded-key --example curseforge_with_embedded_key
//!
//! # Production build with the key baked in:
//! CURSEFORGE_API_KEY=cf_live_xxxxx \
//!     cargo build --release --features embedded-key \
//!     --example curseforge_with_embedded_key
//! ```
//!
//! # GitHub Actions workflow
//!
//! ```yaml
//! # .github/workflows/build.yml
//! jobs:
//!   build:
//!     runs-on: ubuntu-latest
//!     steps:
//!       - uses: actions/checkout@v4
//!       - uses: dtolnay/rust-toolchain@stable
//!       - name: Build with embedded CurseForge key
//!         env:
//!           CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
//!         run: |
//!           cargo build --release --features embedded-key \
//!             --example curseforge_with_embedded_key
//!       - uses: actions/upload-artifact@v4
//!         with:
//!           name: example-binary
//!           path: target/release/examples/curseforge_with_embedded_key*
//! ```
//!
//! The `CURSEFORGE_API_KEY` repository secret never appears in build
//! logs — GitHub Actions masks it automatically. `build.rs` reads it
//! only during compilation; the resulting binary contains obfuscated
//! bytes, not the plaintext.

use hopper_mc::{CurseForgeProvider, ModProvider, Sort};
use secrecy::SecretString;

// Generated by `build.rs` at compile time. Contains:
//   const EMBEDDED_AT_BUILD: bool;
//   const OBFUSCATED_KEY:    &[u8];
//   const OBFUSCATION_MASK:  &[u8];
include!(concat!(env!("OUT_DIR"), "/embedded_key.rs"));

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let key = decode_embedded_key().ok_or(
        "No CurseForge API key was embedded at build time. \
         Build with `CURSEFORGE_API_KEY=<your-key> cargo build --features embedded-key \
         --example curseforge_with_embedded_key`.",
    )?;

    let cf = CurseForgeProvider::new_with_secret_key(Some(key));

    println!("Searching CurseForge for \"sodium\" using the embedded key...\n");
    let hits = cf.find_mods(Some("sodium"), Sort::Relevance, &hopper_mc::SearchFilters::default(), 0, 5).await?;
    for m in hits {
        println!(
            "  {:<32} downloads={:>10}  loaders={:?}",
            truncate(&m.base.title, 32),
            m.base.downloads,
            m.loaders,
        );
    }
    Ok(())
}

/// Reverse the XOR applied at build time and wrap the result in a
/// `SecretString`. Returns `None` when no key was embedded (local dev
/// builds, or CI builds where the secret was not wired up).
///
/// # Why the volatile reads
///
/// Both `OBFUSCATED_KEY` and `OBFUSCATION_MASK` are compile-time
/// constants. A naive implementation —
///
/// ```ignore
/// OBFUSCATED_KEY.iter().zip(OBFUSCATION_MASK).map(|(b, m)| b ^ m).collect()
/// ```
///
/// — looks obfuscated, but LLVM's release-mode constant folder happily
/// evaluates `b ^ m` at compile time and inlines the **plaintext** as a
/// second static array in the binary's `.rdata` section. `strings` then
/// recovers the key instantly; the obfuscation is for nothing.
///
/// `core::ptr::read_volatile` is the portable escape hatch: it is
/// defined to be opaque to the optimizer, so LLVM cannot look through it
/// to constant-fold. The XOR happens at runtime, against values the
/// compiler treats as unknown, so no plaintext copy ends up in the
/// binary.
///
/// # Memory lifetime of the plaintext
///
/// The plaintext exists as a `Vec<u8>` briefly, then is handed off by
/// value into `String::from_utf8` and then into `SecretString`; the
/// `SecretString` destructor zeroes the backing allocation. There is a
/// brief window during the XOR loop itself where the plaintext bytes sit
/// on the heap un-wrapped — callers paranoid about that window should
/// use a platform-specific memory-protection crate (e.g. `memsec::mlock`)
/// to keep the allocation out of swap.
fn decode_embedded_key() -> Option<SecretString> {
    if !EMBEDDED_AT_BUILD || OBFUSCATED_KEY.is_empty() {
        return None;
    }
    let len = OBFUSCATED_KEY.len();
    if OBFUSCATION_MASK.len() != len {
        // Defensive: build.rs should always emit equal-length arrays.
        // If we ever see a mismatch, fail closed rather than leak garbage
        // into the HTTP layer.
        return None;
    }

    let mut plain: Vec<u8> = Vec::with_capacity(len);

    // SAFETY:
    // - Both `OBFUSCATED_KEY` and `OBFUSCATION_MASK` are `'static &[u8]`
    //   whose length we have just checked to be equal to `len`.
    // - The loop index `i` is bounded by `len`, so both `.add(i)` calls
    //   stay within the slice's allocated range.
    // - `read_volatile` on a `*const u8` has no alignment requirement.
    // The volatile reads are load-bearing: they prevent LLVM from
    // constant-folding the XOR at compile time, which would otherwise
    // cause the plaintext key to be baked into the binary as a static
    // array — exactly the leak this obfuscation is trying to prevent.
    unsafe {
        let obf_ptr = OBFUSCATED_KEY.as_ptr();
        let mask_ptr = OBFUSCATION_MASK.as_ptr();
        for i in 0..len {
            let b = core::ptr::read_volatile(obf_ptr.add(i));
            let m = core::ptr::read_volatile(mask_ptr.add(i));
            plain.push(b ^ m);
        }
    }

    let s = String::from_utf8(plain).ok()?;
    // `From<String> for SecretString` hands the allocation off via
    // `into_boxed_str()` — no plaintext copy, and the eventual drop of
    // the `SecretString` zeroes the bytes.
    Some(SecretString::from(s))
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        let mut out: String = s.chars().take(max - 1).collect();
        out.push('…');
        out
    }
}
